# Generated by Django 6.0.6 on 2026-07-04 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='es_administrador',
        ),
    ]
