# Generated by Django 6.0.6 on 2026-09-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compra',
        ),
    ]
