# Generated by Django 6.0.6

import decimal

from django.conf import settings
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("productos", "0003_alter_producto_codigo"),
        ("usuarios", "0003_auditorialog_controlcaja"),
        ("ventas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResolucionFacturacion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("prefijo", models.CharField(max_length=10, unique=True)),
                ("numero_inicial", models.PositiveIntegerField()),
                ("numero_final", models.PositiveIntegerField()),
                ("numero_actual", models.PositiveIntegerField()),
                ("clave_tecnica", models.CharField(blank=True, max_length=100)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("activa", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="FacturaElectronica",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tipo_documento", models.CharField(choices=[("FACTURA", "Factura electrónica"), ("NOTA_CREDITO", "Nota crédito"), ("NOTA_DEBITO", "Nota débito")], default="FACTURA", max_length=20)),
                ("consecutivo", models.PositiveIntegerField()),
                ("numero", models.CharField(max_length=30, unique=True)),
                ("fecha_emision", models.DateTimeField(auto_now_add=True)),
                ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                ("medio_pago", models.CharField(choices=[("EFECTIVO", "Efectivo"), ("TARJETA", "Tarjeta"), ("TRANSFERENCIA", "Transferencia")], default="EFECTIVO", max_length=20)),
                ("estado", models.CharField(choices=[("BORRADOR", "Borrador"), ("GENERADA", "Generada"), ("ENVIADA", "Enviada a DIAN"), ("ACEPTADA", "Aceptada"), ("RECHAZADA", "Rechazada"), ("ANULADA", "Anulada")], default="BORRADOR", max_length=20)),
                ("cliente_nombre", models.CharField(max_length=150)),
                ("cliente_identificacion", models.CharField(blank=True, max_length=50)),
                ("cliente_correo", models.EmailField(blank=True, max_length=254)),
                ("cliente_direccion", models.TextField(blank=True)),
                ("subtotal", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("descuento", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("impuesto", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("total", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("cufe", models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ("xml", models.TextField(blank=True)),
                ("codigo_qr", models.TextField(blank=True)),
                ("respuesta_dian", models.JSONField(blank=True, default=dict)),
                ("observaciones", models.TextField(blank=True)),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                ("actualizada_en", models.DateTimeField(auto_now=True)),
                ("cliente", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="facturas_electronicas", to="clientes.cliente")),
                ("resolucion", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="facturas", to="facturacion.resolucionfacturacion")),
                ("usuario_creacion", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="facturas_creadas", to=settings.AUTH_USER_MODEL)),
                ("venta", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="factura_electronica", to="ventas.venta")),
            ],
            options={"ordering": ["-fecha_emision"]},
        ),
        migrations.CreateModel(
            name="DetalleFacturaElectronica",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("descripcion", models.CharField(max_length=200)),
                ("codigo_producto", models.CharField(max_length=20)),
                ("cantidad", models.PositiveIntegerField()),
                ("precio_unitario", models.DecimalField(decimal_places=2, max_digits=14)),
                ("descuento", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("porcentaje_iva", models.DecimalField(decimal_places=2, default=decimal.Decimal("19.00"), max_digits=5)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=14)),
                ("impuesto", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("total", models.DecimalField(decimal_places=2, max_digits=14)),
                ("detalle_venta", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="detalle_factura", to="ventas.detalleventa")),
                ("factura", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="detalles", to="facturacion.facturaelectronica")),
                ("producto", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="detalles_factura", to="productos.producto")),
            ],
        ),
        migrations.CreateModel(
            name="ImpuestoFactura",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("codigo", models.CharField(max_length=20)),
                ("nombre", models.CharField(max_length=80)),
                ("porcentaje", models.DecimalField(decimal_places=2, max_digits=5)),
                ("base", models.DecimalField(decimal_places=2, max_digits=14)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=14)),
                ("detalle", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="impuestos", to="facturacion.detallefacturaelectronica")),
                ("factura", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="impuestos", to="facturacion.facturaelectronica")),
            ],
        ),
        migrations.CreateModel(
            name="EventoDian",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("codigo", models.CharField(max_length=30)),
                ("estado", models.CharField(max_length=30)),
                ("mensaje", models.TextField(blank=True)),
                ("identificador", models.CharField(blank=True, max_length=100)),
                ("respuesta", models.JSONField(blank=True, default=dict)),
                ("fecha_evento", models.DateTimeField(auto_now_add=True)),
                ("factura", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="eventos_dian", to="facturacion.facturaelectronica")),
            ],
            options={"ordering": ["-fecha_evento"]},
        ),
        migrations.AddConstraint(
            model_name="facturaelectronica",
            constraint=models.UniqueConstraint(fields=("resolucion", "consecutivo"), name="factura_resolucion_consecutivo_unico"),
        ),
    ]
